os: linux

sudo: required

services:
  - docker

language: go

jobs:
  include:
    - name: "tests"
      script:
        - go test

after_success:
  -sh .travis/deploy_docker.sh

notifications:
  email: false