os: linux

sudo: required

services:
  - docker

language: go

jobs:
  include:
    - name: "tests"
      script:
        - go test

after_success:
  - sh .travis/deploy_docker.sh
  - test “$TRAVIS_BRANCH” = “master” && sh .travis/deploy_heroku.sh

notifications:
  email: false