os: linux

sudo: required

services: docker

language: go

jobs:
  include:
    - name: "E2E test"
      script:
        - docker-compose build
        - docker-compose up -d
        - export DB_host=localhost
        - go test tests/user_test.go
        - docker-compose down

notifications:
  email: false