version: '3'
services:
  db:
    container_name: todoapp_postgres
    build:
      ./src/db/
    volumes:
      - .src/db/pgdata:/pgdata
    environment:
     - POSTGRES_DB=todoapp
     - POSTGRES_USER=docker
     - POSTGRES_PASSWORD=docker
     - PGDATA=/pgdata
    ports:
      - "5432"
  app:
    build: .
    volumes:
      - .:/go/src/github.com/bmstu-iu8-g1-2019-project/just-to-do-it/
    command: ["go", "run", "src/main/main.go"]
    ports:
      - "5000:8080"
    depends_on:
      - db
    links:
      - db