version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 3030:3030
  app:
    build: .
    working_dir: /go/src/github.com/bmstu-iu8-g1-2019-project/just-to-do-it
    command: go run ./src/main/main.go -http.addr :8080 -db.host db -db.port 3030 -db.user user -db.password password -db.database db
    volumes:
      - .:/go/src/github.com/bmstu-iu8-g1-2019-project/just-to-do-it/src
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db